server:
  port: 8866

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/
spring:
  application:
    name: order-web